### PR TITLE
Change R objects from S4 to R6 type

### LINKED ISSUE #15: Proper Readme.md

### LINKED ISSUE #19: Rewrite the non-code repo items
DESCRIPTION, INSTALL, NEWS etc.

image

### LINKED ISSUE #36: test-objwrap.r

### LINKED ISSUE #37: test-datetime.r

### LINKED ISSUE #39: Check all `dontrun` examples

### LINKED ISSUE #66: Creation of object from a wrong name should not fail.
```
testClassName <- "Rclr.TestObject"
o <- .External("r_create_clr_object", testClassName, PACKAGE = rSharpEnv$nativePkgName)
```

Now crashes R. Should not happen.

### LINKED ISSUE #68: Include "reflect" into default print method of the R6 object?

### PR DESCRIPTION
**Pull request by PavelBal**
- Fixes #15
- Fixes #19
- Fixes #36
- Fixes #37
- Fixes #39
- Fixes #68
- Fixes #66

### CODE REVIEW

File: shared/ClrFacade/Internal.cs [hunk 1]
```diff
@@ -68,8 +68,12 @@ public static int CallStaticMethod(string typename, string methodName, IntPtr ar
       }
       catch (Exception ex)
       {
-         if (!logThroughR(ex))
-            return -1;
+            if (!logThroughR(ex))
```
Comment (PavelBal) [inline shared/ClrFacade/Internal.cs:71]: @Ian-Du This is how I solved it for static methods.

File: shared/rSharp.cpp [hunk 2]
```diff
@@ -569,8 +569,11 @@ RSharpGenericValue callStatic(const char* mnam, char* ns_qualified_typename, RSh
 
 	auto result = call_static(ns_qualified_typename, mnam, params, numberOfObjects, &return_value);
 
-	if (result < 0)
-		throw std::runtime_error("Error calling static method");
+	if (result < 0) 
+	{
```
Comment (PavelBal) [inline shared/rSharp.cpp:573]: @Ian-Du and then re-throwing to R.

**Review by rwmcintosh — APPROVED** [review]
