### PR TITLE
Fixes #117 rSharp_create_domain should return a flag

### LINKED ISSUE #117: `rSharp_create_domain` should return a flag
Loading assembly might throw an unhandled exception, which crashes R.

### PR DESCRIPTION
**Pull request by rwmcintosh**
Couple of options for discussion. 

If we use ```error_return(ex.what())``` type of return then the following results in RStudio and the process stops
image

I can also return an integer flag instead where flow control could then be used to retry. LMK your preference

### CODE REVIEW

File: shared/rSharp.cpp [hunk 1]
```diff
@@ -27,53 +27,99 @@ typedef intptr_t(CORECLR_DELEGATE_CALLTYPE* CallFullTypeNameDelegate)(RSharpGene
...
+		args = CDR(args);
+
+		const SEXP element = CAR(args);
+		const char* libraryPath = CHAR(STRING_ELT(element, 0));
+
+		// if already loaded in this process, do not load again
+		if (load_assembly_and_get_function_pointer != nullptr)
+		{
+			returnValue = 0;
+			return make_int_sexp(1, &returnValue);
```
Comment (rwmcintosh) [inline shared/rSharp.cpp:71]: This is one approach where we can create different numeric flags for various types of failure.

File: shared/rSharp.cpp [hunk 2]
```diff
@@ -27,53 +27,99 @@ typedef intptr_t(CORECLR_DELEGATE_CALLTYPE* CallFullTypeNameDelegate)(RSharpGene
...
-	delete[] wideStringPath;
+		delete[] wideStringPath;
 #ifdef WINDOWS
-	delete[] wideStringLibraryPath;
+		delete[] wideStringLibraryPath;
 #endif
+	}
+	catch (const std::exception& ex)
+	{
+		error_return(ex.what())
```
Comment (rwmcintosh) [inline shared/rSharp.cpp:117]: another approach where the R interpreter appears to stop processing if this return is used.

**Comment by rwmcintosh** [comment]
Make the return type ```error_return``` instead of flags. No error? return 0

Do the same conversion for rSharp_load_assembly so that ```.External can be used```

File: tests/testthat/test-basic.R [hunk 3]
```diff
@@ -10,7 +10,7 @@ test_that("Methods with variable number of parameters with c# 'params' keyword",
 
 test_that("Vignette examples work", {
   assemblyPath <- system.file("extdata", "rSharp.Examples.dll", package = "rSharp")
-  expect_equal(loadAssembly(assemblyPath)[[1]], assemblyPath)
+  expect_true(loadAssembly(assemblyPath))
```
Comment (rwmcintosh) [inline tests/testthat/test-basic.R:13]: I'm not sure now if you need to modify any documentation about this function but it will return `TRUE` when passing and an error string when failing

**Review by PavelBal — APPROVED** [review]
