### PR TITLE
Fixes #33 Encapsulate each call into try-catch? (#33)

### LINKED ISSUE #33: Encapsulate each call into try-catch?
If an exception is thrown somewhere in C++ code, the whole R session crashes. It would be good to find a way to deal with it, i.e., always forwarding the exception to R instead of simply crashing..

TO reproduce e.g. https://github.com/Open-Systems-Pharmacology/rSharp/issues/32

### PR DESCRIPTION
**Pull request by Ian-Du**

### CODE REVIEW

File: shared/ClrFacade/Internal.cs [hunk 1]
```diff
@@ -13,17 +13,28 @@ public static class Internal
...
 
-      Marshal.StructureToPtr(tempRetVal, returnValue, false);
-      return 1;
+         var result = CallInstanceMethod(instance, methodName, objectArguments);
+         var tempRetVal = RSharpGenericValueExtensions.FromObject(result);
+         Marshal.StructureToPtr(tempRetVal, returnValue, false);
+      }
+      catch (Exception ex)
+      {
+         if (!logThroughR(ex))
```
Comment (rwmcintosh) [inline shared/ClrFacade/Internal.cs:30]: I think we should change how this works for clarity. Functionally it will be the same.

```logThroughR``` always returns false. So, why bother checking it? make the method void and take the if statement away in all these cases.

This makes it look like some decision is being taken, but it's not. We caught an exception and we will return -1 and there will be a string returned in ```returnValue```.

Comment (rwmcintosh) [reply shared/ClrFacade/Internal.cs:30]: In fact, ```logThroughR``` could return a tuple with the exception and string and we would not need the static ```LastCallException```.  I'm pretty sure ```LastException``` is totally unused. Unless it's somehow checked dynamically. I don't think so though because ```Internal``` is completely new class so it would not be accessed directly by R code.

File: shared/ClrFacade/Internal.cs [hunk 2]
```diff
@@ -146,12 +161,22 @@ public static Type GetType(string typename)
...
-      return 1;
+      try
+      {
+         var result = DataConverter?.CurrentObject;
+         var tempRetVal = RSharpGenericValueExtensions.FromObject(result);
+         Marshal.StructureToPtr(tempRetVal, returnValue, false);
+      }
+      catch (Exception ex)
+      {
+         if (!logThroughR(ex))
```
Comment (rwmcintosh) [inline shared/ClrFacade/Internal.cs:172]: Once you have a refactor on the ```logThroughR``` method done, can you pull all this into a single common method. We are always doing the same thing, so it should be only written once and used from everywhere.

Comment (rwmcintosh) [reply shared/ClrFacade/Internal.cs:172]: The common code that can be put into a method is this

```
       if (!logThroughR(ex))
       {
          var tempRetVal = RSharpGenericValueExtensions.FromObject(LastCallException);
          Marshal.StructureToPtr(tempRetVal, returnValue, false);
          return -1;
       }
```

File: shared/rSharp.cpp [hunk 3]
```diff
@@ -518,36 +520,62 @@ SEXP r_create_clr_object(SEXP p) {
...
+		throw std::runtime_error(errorMessage);
+	}
 
-	free_params_array(params, num_objects);
-	return ConvertToSEXP(return_value);
+	return returnValue;
 }
 
-RSharpGenericValue callInstance(RSharpGenericValue** instance, const char* mnam, char* ns_qualified_typename, RSharpGenericValue** params, const R_len_t numberOfObjects)
+RSharpGenericValue callInstance(RSharpGenericValue** instance, const char* calledMethodName, char* ns_qualified_typename, RSharpGenericValue** parameters, const R_len_t numberOfObjects)
```
Comment (rwmcintosh) [inline shared/rSharp.cpp:561]: ```calledMethodName``` is much, much better than mnam. If you did not already replace all mnam with this, please do it! 👍

Comment (rwmcintosh) [reply shared/rSharp.cpp:561]: Likewise ```parameters``` >> ```params```

File: tests/testthat/test-basic.r [hunk 4]
```diff
@@ -158,7 +158,12 @@ test_that("toStringNET works for primitive types", {
 })
 
 # Re-enable when https://github.com/Open-Systems-Pharmacology/rSharp/issues/35 is fixed
```
Comment (rwmcintosh) [inline tests/testthat/test-basic.r:160]: Take that comment out now.

Comment (rwmcintosh) [reply tests/testthat/test-basic.r:160]: ok, also, when running this test I'm not sure how it's counted. I don't see an assert within ```test_that```, so I'm suspicious that it is ignored or skipped or whatever. This is how the test came to you, but see if you can find out how to make this test count as a pass/fail.

Also, don't print anything on the screen if the test passes. Right now I'm seeing some stuff in my RStudio. It's mixed in with all the obsolete stuff too, which @PavelBal is removing in one of his upcoming PR's

```
 Type:    System.Exception
Message: An exception designed with a particular stack trace length
Method:  Void ThrowException(Int32)
Stack trace:
   at ClrFacade.TestCases.ThrowException(Int32 stackDepth)
   at ClrFacade.TestCases.ThrowException(Int32 stackDepth)
   at ClrFacade.TestCases.ThrowException(Int32 stackDepth)
   at ClrFacade.TestCases.ThrowException(Int32 stackDepth)
   at ClrFacade.TestCases.ThrowException(Int32 stackDepth)
   at ClrFacade.TestCases.ThrowException(Int32 stackDepth)
   at ClrFacade.TestCases.ThrowException(Int32 stackDepth)
   at ClrFacade.TestCases.ThrowException(Int32 stackDepth)
   at ClrFacade.TestCases.ThrowException(Int32 stackDepth)
   at ClrFacade.TestCases.ThrowException(Int32 stackDepth)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
```

**Review by rwmcintosh — CHANGES_REQUESTED** [review]
See comments for requested changes

File: shared/ClrFacade/Internal.cs (hunk 1 above)
Comment (Ian-Du) [reply shared/ClrFacade/Internal.cs:30]: there is a function in R thats called printTraceback that uses/gets the LastException. I believe this was how we dealt with exceptions in the old code. I kept it as is so that it can still be used, just in case.

Comment (PavelBal) [reply shared/ClrFacade/Internal.cs:30]: `LastException` is used by the R function `printTraceback()` which prints the last exception. The reason is that R truncates error messages, so sometime it could be useful to call it.

`Internal` is not really new, its contents were in `ClrFacade` and yes, it broke some R code and I had to use the new assembly name ;)

File: tests/testthat/test-basic.r (hunk 4 above)
Comment (PavelBal) [reply tests/testthat/test-basic.r:160]: Don't care about R stuff at this stage.

File: shared/ClrFacade/Internal.cs (hunk 1 above)
Comment (rwmcintosh) [reply shared/ClrFacade/Internal.cs:30]: So you want to keep this printTraceback()? If so, then the LastException or whatever should be moved, or proxied in ClrFacade instead.

Comment (rwmcintosh) [reply shared/ClrFacade/Internal.cs:30]: Also add tests to make sure the proxies stay working.

**Review by rwmcintosh — APPROVED** [review]
