### PR TITLE
Fix for sending/receiving NULL and NAN values

### LINKED ISSUE #57: Implement tests for NULL, NaN and NA
- [x] R sends `NA` to .NET
- [x] R sends `NaN` to .NET
- [x] R sends `NULL` to .NET
- [ ] .NET sends `NA` to R
- [x] .NET sends `NaN` to R
- [x] .NET sends `NULL` to R

- [ ] R sends array [1, `NA`, 3] to .NET
- [ ] R sends array [1, `NaN`, 3] to .NET
- [ ] R sends array [1, `NULL`, 3] to .NET
- [ ] .NET sends array [1, `NA`, 3] to R
- [ ] .NET sends array [1, `NaN`, 3] to R
- [ ] .NET sends array [1, `NULL`, 3] to R

### PR DESCRIPTION
**Pull request by Ian-Du**
Based on @PavelBal  #110  and #111  shows  what RSharp initially sees for theses values. On closer inspection  the are seen as the following:
NULL -> NILSXP (in C++) -> in C# its kept as a null value object
NA -> LGLSXP(in C++ as a logical sexpression) -> logical vector(in C# symbolic expression)-> bool (true)(in C# primitive types)
NAN -> REALSXP(in C++ real sexpression)-> numeric vector(in C# symbolic expression)-> double (double.NaN)(in C# primitive types)

The issue with NA is that it is considered a logical vector which translates to a boolean and this makes it difficult to differentiate from an actual bool values.

Fixes #57

### CODE REVIEW

**Comment by PavelBal** [comment]
Fixes #57

File: shared/ClrFacade/TestCases.cs [hunk 1]
```diff
@@ -689,6 +689,35 @@ public static ITestGenericInterface<string>[] CreateTestArrayGenericInterface()
...
+      return obj;
+   }
+
+   public static object IsNaN(object obj)
+   {
+      if ((double?)obj == null) 
+         return false;
+
+      return double.IsNaN((double)obj);
+   }
```
Comment (rwmcintosh) [inline shared/ClrFacade/TestCases.cs:709]: Can you rewrite this with safe-cast style. 

like this
```
      if (!(obj is double d)) 
         return false;

      return double.IsNaN(d);
```

This safe-cast style makes it easier to read.

File: shared/ClrFacade/TestCases.cs [hunk 2]
```diff
@@ -689,6 +689,35 @@ public static ITestGenericInterface<string>[] CreateTestArrayGenericInterface()
          result[i] = new ImplITestGenericInterface();
       return result;
    }
+   
+   public static object IsNull(object obj)
+   {
+      return (obj == null);
```
Comment (rwmcintosh) [inline shared/ClrFacade/TestCases.cs:695]: you can drop the braces

```
return obj == null;
```

**Review by PavelBal — CHANGES_REQUESTED** [review]

File: shared/ClrFacade/TestCases.cs [hunk 3]
```diff
@@ -689,6 +689,35 @@ public static ITestGenericInterface<string>[] CreateTestArrayGenericInterface()
...
+
+   public static object GetNull()
+   {
+      return null;
+   }
+
+   public static object GetNaN()
+   {
+      
+      return Double.NaN;
```
Comment (rwmcintosh) [inline shared/ClrFacade/TestCases.cs:719]: In most cases we use the keyword instead of the base type. It's one of those conventions that we use in Suite.

eg. 
```
double.NaN 
```

You will see this all over the place in OSPSuite, but mainly with string manipulation
```
string.IsNullOrEmpty(someVariable)
```

rather than

```
String.IsNullOrEmpty(someVariable)
```

File: shared/ClrFacade/TestCases.cs [hunk 4]
```diff
@@ -840,6 +869,7 @@ public static int StaticGetMethodWithParameters(int pOne, string pTwo)
    public static int StaticPropertyIntegerOne { get; set; }
    public static int StaticPropertyIntegerTwo { get; set; }
 
+
```
Comment (rwmcintosh) [inline shared/ClrFacade/TestCases.cs:872]: Remove that extra newline here.

File: shared/rSharp.cpp [hunk 5]
```diff
@@ -1066,7 +1066,8 @@ RSharpGenericValue ConvertToRSharpGenericValue(SEXP s)
 	RSharpGenericValue result;
 
 	int typeof = TYPEOF(s);
-	switch (typeof) {
+	switch (typeof)
+	{
```
Comment (rwmcintosh) [inline shared/rSharp.cpp:1070]: Yes! Fix whenever you find this!

File: tests/testthat/test-array.R [hunk 6]
```diff
@@ -39,7 +39,7 @@ test_that("Basic types of length zero are passed correctly from R to .NET", {
 })
 
 # Same for length 1!
-# Investigate after https://github.com/Open-Systems-Pharmacology/rSharp/issues/35
+# https://github.com/Open-Systems-Pharmacology/rSharp/issues/108
```
Comment (rwmcintosh) [inline tests/testthat/test-array.R:42]: Can you also link this to the issue if it hasn't already been done. You can paste a link to a line of code.

Comment (rwmcintosh) [reply tests/testthat/test-array.R:42]: This might be a line from @PavelBal originally

File: tests/testthat/test-utilities-static.R [hunk 7]
```diff
@@ -6,6 +6,7 @@ test_that("callStatic returns a NetObject when the static .NET method returns a
   testObj <- callTestCase("CreateTestObjectGenericInstance")
   expect_true(inherits(testObj, "NetObject"))
   # 2DO: Test for IS!
+  # https://github.com/Open-Systems-Pharmacology/rSharp/issues/67
```
Comment (rwmcintosh) [inline tests/testthat/test-utilities-static.R:9]: Make a link in the issue to this line @PavelBal so the future dev who works on it can easily find this from the issue

**Review by rwmcintosh — CHANGES_REQUESTED** [review]
For me, the C# is pretty good. Just a couple style/convention tips.

I'll review again if there are more changes coming.

File: shared/ClrFacade/TestCases.cs [hunk 8]
```diff
@@ -689,6 +689,35 @@ public static ITestGenericInterface<string>[] CreateTestArrayGenericInterface()
...
+   }
+
+   public static object GetNull()
+   {
+      return null;
+   }
+
+   public static object GetNaN()
+   {
+
```
Comment (rwmcintosh) [inline shared/ClrFacade/TestCases.cs:718]: remove the newline

File: tests/testthat/test-array.R (hunk 6 above)
Comment (PavelBal) [reply tests/testthat/test-array.R:42]: Yes this if from me, and it will not be fixed in this PR

File: tests/testthat/test-utilities-static.R (hunk 7 above)
Comment (PavelBal) [reply tests/testthat/test-utilities-static.R:9]: Done

File: tests/testthat/test-null-na-nan.R [hunk 9]
```diff
@@ -0,0 +1,52 @@
...
+test_that("Array NULL is passed from .NET as null", {
+  expect_equal(callTestCase("GetNULLArray", c(1, NULL, 3)))
+})
+# No such concept in .NET
+#https://github.com/Open-Systems-Pharmacology/rSharp/issues/110
+# test_that("Array NA is passed from .NET as NA", {
+#   expect_equal(callTestCase("GetNAArray", c(1, NA, 3)))
+# })
+test_that("Array NaN is passed from .NET as NaN", {
+  expect_equal(callTestCase("GetNaNlArray", c(1, NaN, 3)))
```
Comment (rwmcintosh) [inline tests/testthat/test-null-na-nan.R:51]: ```NanlArray``` ?

**Comment by rwmcintosh** [comment]
Ok, I tried to run the tests on Linux and they don't pass, then I tried on Windows and they also don't pass. Should this be made into draft?

File: tests/testthat/test-null-na-nan.R (hunk 9 above)
Comment (PavelBal) [reply tests/testthat/test-null-na-nan.R]: Typo, thanks.

**Comment by PavelBal** [comment]
I asked to add four tests in .NET:

- IsNaNInArray
- IsNullInArray
- GetNULLArray
- GetNaNArray

They are called from R, thats why it is failing.

**Comment by Ian-Du** [comment]
@PavelBal we made some changes to accommodate the Null in array in the GetNULLArray() test which checks each element for their type. While this process shouldn't be taxing (since it uses a dictionary  as a sort of buffer), just something to think about/keep in mind if an event where it needs to process an array with hundreds or thousands of elements would cause a significant slow down

File: shared/ClrFacade/TestCases.cs [hunk 10]
```diff
@@ -6,6 +6,7 @@
 using System.Linq;
 using System.Numerics;
 using System.Text;
+using System.Threading;
```
Comment (rwmcintosh) [inline shared/ClrFacade/TestCases.cs:9]: That's probably not used and could be removed?

**Review by rwmcintosh — APPROVED** [review]
just address a couple of comments regarding extra newline and unnecessary ```using``` statements.

For C# code. Did not review any R code.

**Comment by PavelBal** [comment]
>  just something to think about/keep in mind if an event where it needs to process an array with hundreds or thousands of elements would probably cause a slow down

If a code change has been introduced that could cause a slow down, I need to undestand it better.

**Comment by rwmcintosh** [comment]
> > just something to think about/keep in mind if an event where it needs to process an array with hundreds or thousands of elements would probably cause a slow down
> 
> If a code change has been introduced that could cause a slow down, I need to undestand it better.

I'll comment in the code, but I don't expect it to be a big issue.

File: shared/ClrFacade/InternalRDotNetDataConverter.cs [hunk 11]
```diff
@@ -574,13 +584,10 @@ private SymbolicExpression convertToList(Array array)
    {
       if (array.Rank > 1)
          throw new NotSupportedException("Generic array converter is limited to uni-dimensional arrays");
-
-      // CAUTION: The following, while efficient, means that more specialized converters
-      // will not be picked up.
-      var elementConverter = tryGetConverter(array.GetType().GetElementType());
```
Comment (rwmcintosh) [inline shared/ClrFacade/InternalRDotNetDataConverter.cs:580]: In the old way, we looked up the type converter once for an array. So, if it's an array of floats, we get a converter that converts floats. Simple types all have their own converter and then anything that's not simple is converted as an object. 

So it worked as long as the array had a specific enough type or was an array of all objects. We needed to change this so that specific types in the array could be converted by their own converters. If an array of objects has a `float`, we want to convert that element as a `real` and the rest as an `object`.

We saw this note ```CAUTION```, so we were wary.

File: shared/ClrFacade/InternalRDotNetDataConverter.cs [hunk 12]
```diff
@@ -324,13 +324,22 @@ private GenericVector convertDictionary<T>(object obj)
...
-         sexpArray[i] = converter == null ? convertToSexp(objects[i]) : converter(objects[i]);
-
+      {
+         if (objects[i] == null)
+         {
+            sexpArray[i] = _engine.NilValue;
+         }
+         else
+         {
+            var elementConverter = tryGetConverter(objects[i].GetType());
```
Comment (rwmcintosh) [inline shared/ClrFacade/InternalRDotNetDataConverter.cs:339]: this converter lookup is now done _per-element_ instead of _per-array_

what is involved in a converter lookup? Is it expensive?

Comment (rwmcintosh) [reply shared/ClrFacade/InternalRDotNetDataConverter.cs:339]: Here's the code for it

```
   private Func<object, SymbolicExpression> tryGetConverter(Type t)
   {
      return _converterFunctions.GetValueOrDefault(t);
   }
```

_converterFunctions is a Microsoft Dictionary object

```
   private readonly Dictionary<Type, Func<object, SymbolicExpression>> _converterFunctions;
```

`GetValueOrDefault` is an extension method from .NET. I doubt we would be able to write anything faster. If we profile and find a big difference then we could implement a check if the key exists in the dictionary first. But I would be shocked if that was not exactly how this is already done.

Comment (rwmcintosh) [reply shared/ClrFacade/InternalRDotNetDataConverter.cs:339]: oh, the way to test if this has a big impact is to send a big array of objects that have no converter in the dictionary.

**Review by PavelBal — APPROVED** [review]
